[SIMULATION]
randomize_positions = True
calculate_sizes = True
end_on_collision = False
size_scale_factor = 1
debug = True

simulation_cycles = 100000000
body_mask = 2
min_velocity = -100e5
max_velocity = 100e5
time_step = 0.01

[VISUALIZATION]
grid_width = 100000000000
grid_height = 100000000000
plot_dpi = 100

[OUTPUT]
save_plots = True
high_quality_plots = True
frame_interval = 100
min_frames = 250
max_retries = 100

#[planet.EARTH]
#mass = 100% earth mass = 5.97e24 kg
#size = 10.0
#pos_x = 250.0
#pos_y = 250.0
#vel_x = 0.0
#vel_y = 0.0

#[star.SUN]
#mass = 100% sun mass = 1.989e30 kg
#size = 10.0
#pos_x = 250.0
#pos_y = 250.0
#vel_x = 0.0
#vel_y = 0.0

[planet.Proxima b ]
mass = 5.97e24
size = 10.0
pos_x = 175.0
pos_y = 100.0
vel_x = -0.01
vel_y = 0.03

[planet.Proxima d ]
mass = 5.97e24
size = 10.0
pos_x = 175.0
pos_y = 250.0
vel_x = 0.0
vel_y = -0.1

[star.Rigil Kentaurus]
mass = 5.97e24
size = 10.0
pos_x = 250.0
pos_y = 175.0
vel_x = -0.03
vel_y = -0.03

[star.Toliman]
mass = 5.97e24
size = 10.0
pos_x = 100
pos_y = 175
vel_x = 0.1
vel_y = 0.03

[star.Proxima Centauri]
mass = 5.97e24
size = 10.0
pos_x = 175.0
pos_y = 175.0
vel_x = 0.0
vel_y = 0.0
