[SIMULATION]
randomize_positions = True
calculate_sizes = True
size_scale_factor = 100
debug = True

simulation_cycles = 100000000
time_step = 0.01
min_velocity = -0.2
max_velocity = 0.2

[VISUALIZATION]
grid_width = 300
grid_height = 300
scale_factor = 0.1  
plot_dpi = 100

[OUTPUT]
save_plots = True
high_quality_plots = True
frame_interval = 500
min_frames = 100
max_retries = 100

[BODIES]
#[BODY_NAME]
#mass = 0.8
#size = 10.0
#pos_x = 250.0
#pos_y = 250.0
#vel_x = 0.0
#vel_y = 0.0

[mercury]
mass = 0.112
size = 10.0
pos_x = 20.0
pos_y = 20.0
vel_x = 0.0
vel_y = 0.0

[mars]
mass = 0.466
size = 10.0
pos_x = 280.0
pos_y = 20.0
vel_x = 0.0
vel_y = 0.0

[valeria]
mass = 0.652
size = 10.0
pos_x = 20.0
pos_y = 280.0
vel_x = 0.0
vel_y = 0.0

[venus]
mass = 0.612
size = 10.0
pos_x = 280.0
pos_y = 280.0
vel_x = 0.0
vel_y = 0.0
